language: cpp
compiler:
 - clang
 - gcc
before_install:
 - sudo apt-get install -y g++-4.9
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
 - gcc --version
 - g++ --version
install:
 - make

script:
 - run.test
