language:
 - cpp

compiler:
 - clang
 - gcc

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get -qq install libboost-all-dev -y
 - sudo apt-get -qq install g++-4.9 -y

install:
 - make

script:
 - ./run.test
